### ISSUE TITLE
This doesn't seem to work?

### ISSUE THREAD

**Issue by amihaiemil** [rahmanusta/servlet4-push#1]
I run your example exactly as explained, with the latest glassfish5 nightly build and Chrome version 60. JDK version is 1.8.0_144:

![image](https://user-images.githubusercontent.com/6305156/29493946-fcdf10ba-85a8-11e7-95c1-5d8485d13611.png)

git clone, maven build, everything works fine, but then I deploy to the server, make the request, and all the resources load via http/1.1: 

![image](https://user-images.githubusercontent.com/6305156/29493959-29238e1c-85a9-11e7-8213-e92f9f333406.png)

Did you encounter this recently?

Also, what seems strange to me, is that the Response Header ``X-Powered-By``, set by Glassfish5, starts with ``Servlet/3.1 ...``, and I believe it should start with ``Servlet/4 ... ``

I did find this article: https://www.nginx.com/blog/supporting-http2-google-chrome-users/
Could it be that Chrome doesn't support http2 out of the box?

**Comment by amihaiemil** [comment]
I've also asked @adambien and @delabassee, maybe one of them knows the answer :D

**Comment by rahmanusta** [comment]
@amihaiemil  Is it possible that you have used HTTP instead of HTTPS?

If you use Docker, you can test it like below;

`docker run -it --rm -d -p 8181:8181 rahmanusta/servlet4-push`

Then open https://localhost:8181/Servlet4Push/http2

**Comment by amihaiemil** [comment]
@rahmanusta Right, I didn't know HTTPS was mandatory. I'll try the docker option and let you know :)

**Comment by amihaiemil** [comment]
@rahmanusta Ok, it worked fine with HTTPS. Thanks for the fast response. Could you maybe add this in your article? I didn't know HTTPS was mandatory and I don't understand why it is, I have to study the topic more :D

**Comment by rahmanusta** [comment]
Yes, it is missing in the article. Could you please edit my article here with your words. https://github.com/rahmanusta/servlet4-push/blob/master/README.adoc

**Comment by amihaiemil** [comment]
Closing this, thanks.
