### ISSUE TITLE
addHeader use is wrong

### ISSUE THREAD

**Issue by verhas** [rahmanusta/servlet4-push#3]
You call `addHeader()` on the push builder to add content type signaling the type of the content for the download. The documentation of this method says that you can set a header for the request. The content type will be set by the server when it delivers the content.

Since the request type by default is `GET` and there is no body in the request setting the content type for the request makes no harm except it is misleading and as such it is a serious issue in a tutorial like project.

**Comment by rahmanusta** [comment]
I don't see there is an issue, but you can make a pull request. It is just a tutorial to show HTTP/2 server push with Servlet 4, not target for production.
